# Generated by Django 4.1.3 on 2022-12-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Barras', models.IntegerField()),
                ('Codigo', models.CharField(max_length=20)),
                ('Relacional', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=200)),
                ('Precio', models.CharField(max_length=20)),
                ('Porcentaje', models.CharField(max_length=4)),
                ('Pack', models.CharField(max_length=20)),
                ('Final', models.CharField(max_length=20)),
                ('Trabajado', models.CharField(max_length=20)),
                ('Actualizado', models.CharField(max_length=20)),
                ('Fecha', models.CharField(max_length=20)),
                ('Stock', models.CharField(max_length=20)),
                ('Probeedores', models.CharField(max_length=20)),
                ('Cantidad', models.CharField(max_length=20)),
                ('Imagen', models.CharField(max_length=20)),
            ],
        ),
    ]
