# Generated by Django 4.1.3 on 2023-01-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Agregado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Editado',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
