# Generated by Django 4.1.3 on 2023-01-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_remove_item_cantidad_alter_item_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='Barras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Pack',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='Trabajado',
            field=models.BooleanField(default=False),
        ),
    ]
