# Generated by Django 4.1.3 on 2023-01-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('/A', 'Amaya'), ('/B', 'Bauen'), ('/C', 'Cedica'), ('/Cr', 'Crimaral'), ('/Dx', 'Danirox'), ('/3D', 'Dist3D'), ('/Cb', 'CityBell'), ('/E', 'Econo'), ('/Eq', 'EQ'), ('/Fp', 'FerriPlast'), ('/F', 'Fischer'), ('/M', 'Maglia'), ('/P', 'Parsecs'), ('/Sn', 'Sibon'), ('/S', 'Sumar'), ('/V', 'Violini'), ('/Y', 'YAYI')], default='/A', max_length=5)),
                ('numero_factura', models.IntegerField(default=0)),
                ('tipo_de_factura', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('numero_del_tipo', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro_General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Negro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_1', models.FloatField(default=0.0)),
                ('subtotal_2', models.FloatField(default=0.0)),
                ('iva_21', models.FloatField(default=0.0)),
                ('iva_10_5', models.FloatField(default=0.0)),
                ('total_1', models.FloatField(default=0.0)),
                ('total_2', models.FloatField(default=0.0)),
                ('total_final', models.FloatField(default=0.0)),
                ('factura_proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.factura_proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Blanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_1', models.FloatField(default=0.0)),
                ('subtotal_2', models.FloatField(default=0.0)),
                ('iva_21', models.FloatField(default=0.0)),
                ('iva_10_5', models.FloatField(default=0.0)),
                ('total_1', models.FloatField(default=0.0)),
                ('total_2', models.FloatField(default=0.0)),
                ('total_final', models.FloatField(default=0.0)),
                ('factura_proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.factura_proveedor')),
            ],
        ),
    ]
