# Generated by Django 4.1.4 on 2022-12-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Usuario", models.CharField(max_length=20)),
                ("Codigo", models.CharField(max_length=20)),
                ("Nombre", models.CharField(max_length=20)),
                ("Cantidad", models.CharField(max_length=20)),
                ("Precio", models.CharField(max_length=20)),
            ],
        ),
    ]
