# Generated by Django 4.0.6 on 2022-12-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicionales',
            fields=[
                ('tipo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=1)),
                ('Nombre', models.CharField(max_length=1)),
                ('Precio', models.CharField(max_length=1)),
                ('Porcentaje', models.FloatField()),
                ('Inicio', models.CharField(max_length=2)),
                ('Extension', models.CharField(max_length=20)),
            ],
        ),
    ]
