# Generated by Django 4.1.3 on 2022-12-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicionales',
            fields=[
                ('proveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('col_codigo', models.CharField(max_length=1)),
                ('col_nombre', models.CharField(max_length=1)),
                ('col_precio', models.CharField(max_length=1)),
                ('dolar', models.FloatField(default=0.0, max_length=29)),
                ('porcentaje', models.FloatField()),
                ('inicio', models.CharField(max_length=2)),
                ('extension', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=20)),
                ('condicion', models.CharField(max_length=20)),
                ('dolar', models.FloatField(max_length=29)),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sin_Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
            ],
        ),
    ]
