# Generated by Django 4.1.3 on 2022-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizador', '0003_remove_proveedores_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(choices=[('/B', 'Bauen'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='/B', max_length=4),
        ),
    ]
