# Generated by Django 4.1.3 on 2023-01-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizador', '0004_alter_proveedores_archivo_alter_proveedores_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(choices=[('/A', 'Amaya'), ('/B', 'Bauen'), ('/C', 'Cedica'), ('/Cr', 'Crimaral'), ('/Dx', 'Danirox'), ('/3D', 'Dist3D'), ('/Cb', 'CityBell'), ('/E', 'Econo'), ('/Eq', 'EQ'), ('/Fp', 'FerriPlast'), ('/F', 'Fischer'), ('/M', 'Maglia'), ('/P', 'Parsecs'), ('/Sn', 'Sibon'), ('/S', 'Sumar'), ('/V', 'Violini'), ('/Y', 'YAYI')], default='/A', max_length=4),
        ),
    ]
