# Generated by Django 4.1.3 on 2023-01-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizador', '0005_alter_proveedores_fecha_alter_proveedores_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
