# Generated by Django 4.1.3 on 2023-01-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizador', '0006_alter_proveedores_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='fecha',
            new_name='agregado',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='editado',
            field=models.DateField(auto_now=True),
        ),
    ]
