# Generated by Django 4.1.3 on 2023-01-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualizador', '0004_alter_proveedores_archivo'),
        ('actualizador', '0007_rename_fecha_proveedores_agregado_and_more'),
    ]

    operations = [
    ]
