# Generated by Django 4.0.6 on 2022-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor', models.CharField(max_length=20)),
                ('Codigo_lista', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=20)),
                ('Cantidad', models.CharField(max_length=20)),
            ],
        ),
    ]
