# Generated by Django 4.0.6 on 2022-12-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla_Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=20)),
                ('Hora', models.CharField(max_length=20)),
                ('Efectivo', models.CharField(max_length=20)),
                ('Cant_efectivo', models.CharField(max_length=20)),
                ('Visa_credito', models.CharField(max_length=20)),
                ('Cant_visa_credito', models.CharField(max_length=20)),
                ('Master_credito', models.CharField(max_length=20)),
                ('Cant_master_credito', models.CharField(max_length=20)),
                ('Visa_debito', models.CharField(max_length=20)),
                ('Cant_visa_debito', models.CharField(max_length=20)),
                ('Maestro', models.CharField(max_length=20)),
                ('Cant_maestro', models.CharField(max_length=20)),
                ('Caja_inicial', models.CharField(max_length=20)),
                ('Caja_final', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=20)),
                ('Blanco', models.CharField(max_length=20)),
                ('Negro', models.CharField(max_length=20)),
                ('Diferencia', models.CharField(max_length=20)),
                ('Total_diario', models.CharField(max_length=20)),
                ('Credito', models.CharField(max_length=20)),
                ('Debito', models.CharField(max_length=20)),
                ('Mercado_pago', models.CharField(max_length=20)),
                ('Venta_online', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_Mensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=20)),
            ],
        ),
    ]
